service: voice-chatgpt-server

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: ap-northeast-1

plugins:
  - serverless-python-requirements

functions:
  chatgpt-audio-chatbot:
    handler: handler.handler
    # 告訴伺服器要用handler中的handler function
    timeout: 30
    events:
      - http:
          path: get-answer
          method: post
          cors: true
    # 接收到前端POST的get-answer以後執行的方法